language: java
sudo: false
install:
  - mvn --settings .travis/settings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
before_install:
  - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import; fi
  - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi
addons:
  sonarcloud:
    organization: "sbaudoin-github"
    token:
      secure: "m88KirUCH0/d7o2u19b1vBOyQOcMLXQmlAx3GdoYNQgOdjzLVqHUV70+FmIeVM/DqgzyUG31BZkwWR5mpl0S7ZKQ3IlES6xPp7xvf4QbVsmVoWTBce69/Nfn2YsecmEFGwhRJ4+0ehxaE3/3NL0WDCCCkVbnpsVaiCaru+b1jdmX5VvX0yIOM8lmKStr1Tbdvb05tCl0dN6Q4bZUU/hMw/RXHLG9+kiDFB94Wuo7QUiZA+lAA9//tnPCaYHtAOF9HVByBZTQdYJghwX0RnR3y7irtsLaW48r1EHO+2I/dHzJKXX131ZR2f9M2UuSk5fOTQ59emcLWKA6ILeeVdYyNr/V7ZmcS70j3YzhQE6Q05KzEqG090onRltq3r8J+OmlzjNUE0Zw6EU4wrCA2zBCQUvUHyyMiXsCe892GiBSU55BVTa7RBOSo2zrYhR9GOXKIv6uVIqavlOOKOXKF3+8AZZcc0uABEnR9YD9QfU9zXsTzZhYTuvIQ1a0XUsueSVRYpzr6hS+o8l4FFOC0PSskeelWFFlbM2CpDUCc5netRi9M44y9yCxC0S+DemUuKxRd8TpRAI4EWADkQUuYg4YagDQzirZZTORmYjURwDxYRUebi/VMh6vPam6e7oTr3EqlBsEQSeHa7Cl/9lsCMzFRFNfMO6+BmPmzzf0W2vYRh4="
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
deploy:
  - provider: script
    script: bash .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: sbaudoin/sonar-yaml
      all_branches: true
  - provider: releases
    api_key:
      secure: "kiGVs8LRsaEtrluxsMx77ZZsP491VGfyF6dA2+/qTfLih1VGxuhtNndsa9oUOfUlhCptaLDULWQYc+lD3qvf9ffXZHirpFi1Qe1GbH5kom7F/DybFLrGyhqK+ma6iUB8vRAqeRd/RSu5tzBFxdzELD058Wio2ziUWs2+55QFaqj8X3tCMLpDerm82UNBmnBVyw3gT1YV0vFmDl3Y8jgr615xWwwhjJ7DKu0265UkfIh9yWRHS6ThTnLAvNNH3AFEqJzevNxyM0/n9TBR6lNcXJlBb9QuQS32//Y0j03SaxKjb5OmjTvhnoY2vdLnOc22la2eiK3aWTMkQXdSFBFbXdDzEZqtxwKp5+24069apBQUqu2u/af2VGIKOI7bPr5wKOmwA+Hs9fEqh5PJiiaxmssDgrUxLfuuJySa/IjFXnAeNyX0LEkU5EFvvNq21QWI+MJhCfbaMl/xj3C0rUEHLOCtd99svKOi8bUR+9XUkz33ucnUaIWmDVXlwOyVCGp8HQTrRQ2hypZgfMeXnQUe/oGVGfiGOQJwiZpo5FK2MPhX/5MX+9/xkvEV1DtwgUXZXNOCoQvagHKuJXNgzGH7rFUNBsqYKYocfjO63JB2Yk7NitUuRD/o0kHDv5HUgYWNlhhWkmzKUZ5n9BNoGBywafjkhk7UL+1QtCwCA5bKQN4="
    file_glob: true
    file:
      - target/sonar-yaml-plugin-*.jar
    skip_cleanup: true
    on:
      repo: sbaudoin/sonar-yaml
      tags: true
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
