language: java
sudo: false
install:
  - mvn --settings .travis/settings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
before_install:
  - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import; fi
  - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi
addons:
  sonarcloud:
    organization: "sbaudoin-github"
    token:
      secure: "m88KirUCH0/d7o2u19b1vBOyQOcMLXQmlAx3GdoYNQgOdjzLVqHUV70+FmIeVM/DqgzyUG31BZkwWR5mpl0S7ZKQ3IlES6xPp7xvf4QbVsmVoWTBce69/Nfn2YsecmEFGwhRJ4+0ehxaE3/3NL0WDCCCkVbnpsVaiCaru+b1jdmX5VvX0yIOM8lmKStr1Tbdvb05tCl0dN6Q4bZUU/hMw/RXHLG9+kiDFB94Wuo7QUiZA+lAA9//tnPCaYHtAOF9HVByBZTQdYJghwX0RnR3y7irtsLaW48r1EHO+2I/dHzJKXX131ZR2f9M2UuSk5fOTQ59emcLWKA6ILeeVdYyNr/V7ZmcS70j3YzhQE6Q05KzEqG090onRltq3r8J+OmlzjNUE0Zw6EU4wrCA2zBCQUvUHyyMiXsCe892GiBSU55BVTa7RBOSo2zrYhR9GOXKIv6uVIqavlOOKOXKF3+8AZZcc0uABEnR9YD9QfU9zXsTzZhYTuvIQ1a0XUsueSVRYpzr6hS+o8l4FFOC0PSskeelWFFlbM2CpDUCc5netRi9M44y9yCxC0S+DemUuKxRd8TpRAI4EWADkQUuYg4YagDQzirZZTORmYjURwDxYRUebi/VMh6vPam6e7oTr3EqlBsEQSeHa7Cl/9lsCMzFRFNfMO6+BmPmzzf0W2vYRh4="
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
deploy:
  - provider: script
    script: bash .travis/deploy.sh
    skip_cleanup: true
    on:
      repo: sbaudoin/sonar-yaml
      all_branches: true
  - provider: releases
    api_key:
      secure: "53l0MDglsUl8cbn2diuJLvFaNSyfpVeC3pCTerj1T/y2dkpcGU8v4/LZzFMZePiGp8deikfLyqoZHnoI/bOesKKLCNdjeDoPBecGHq2lKpdCiduwsk5OX9eQsHszfR1JtswIx1N+HfYhziJw7/0p2u0ptng+m6RA29kXnMJ+6wG1wl08stebntjscASpq4DmnEj90Kb1YFBinrp8tc14WpKVRzV5ocS6isDe6BKTYz/xZa5A2BEoTOd1ATfSS65pCNtjJ5cDzeyW4NaqUS9IwDQvDRX+frECsnlxWFTwpCYh9DhLjumBygoOg0IA21LoREU0DK2poRhThrKZ3IqWUWgGwLL86NdnnI84fMho66x7FIuAq5WJfXBQ9hA/ThUx0WVdCNf3SrIPF43SjvkgYhILfdAHBrbIlCiqEKOGfmJQ7Sfzm2qkW/GJzk5GNyoe3HZgnBA9hyO38k1XY6XvzXJzZ4y3gH2/3olNGdUV2wZjUtKC4v755UNDwBSzI3qTzCpq4zFIOjZIeVCk/8IJxcOlLsOUZEo6PWI8NYV3DtW7cSIci5pLvRugEQ0H68E2PEIybHNoZJA0BOitq2TWsOEEqbpDNYqGN3PVgOpjR+ULmp7Kwny/dsLoG6XZgc/dv3T98egG2xNiRFOpJfXmgDOQSZF+J1VzV3wZmrKaSxo="
    file_glob: true
    file:
      - target/sonar-yaml-plugin-*.jar
    skip_cleanup: true
    on:
      repo: sbaudoin/sonar-yaml
      tags: true
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
