language: java
sudo: false
env:
  - MAVEN_VERSION=$(grep '<version>' pom.xml | head -1 | sed 's/<\/\?version>//g'| awk '{print $1}')
install:
  - mvn --settings .travis/settings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
before_install:
  - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import; fi
  - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi
addons:
  sonarcloud:
    organization: "sbaudoin-github"
    token:
      secure: "m88KirUCH0/d7o2u19b1vBOyQOcMLXQmlAx3GdoYNQgOdjzLVqHUV70+FmIeVM/DqgzyUG31BZkwWR5mpl0S7ZKQ3IlES6xPp7xvf4QbVsmVoWTBce69/Nfn2YsecmEFGwhRJ4+0ehxaE3/3NL0WDCCCkVbnpsVaiCaru+b1jdmX5VvX0yIOM8lmKStr1Tbdvb05tCl0dN6Q4bZUU/hMw/RXHLG9+kiDFB94Wuo7QUiZA+lAA9//tnPCaYHtAOF9HVByBZTQdYJghwX0RnR3y7irtsLaW48r1EHO+2I/dHzJKXX131ZR2f9M2UuSk5fOTQ59emcLWKA6ILeeVdYyNr/V7ZmcS70j3YzhQE6Q05KzEqG090onRltq3r8J+OmlzjNUE0Zw6EU4wrCA2zBCQUvUHyyMiXsCe892GiBSU55BVTa7RBOSo2zrYhR9GOXKIv6uVIqavlOOKOXKF3+8AZZcc0uABEnR9YD9QfU9zXsTzZhYTuvIQ1a0XUsueSVRYpzr6hS+o8l4FFOC0PSskeelWFFlbM2CpDUCc5netRi9M44y9yCxC0S+DemUuKxRd8TpRAI4EWADkQUuYg4YagDQzirZZTORmYjURwDxYRUebi/VMh6vPam6e7oTr3EqlBsEQSeHa7Cl/9lsCMzFRFNfMO6+BmPmzzf0W2vYRh4="
jdk:
  - oraclejdk8
script:
  - echo "Building version $MAVEN_VERSION"
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
deploy:
  # Only the master branch is entitled to deployment for snapshots
  - provider: script
    script: [[ $MAVEN_VERSION =~ -SNAPSHO$ ]] && mvn --settings .travis/settings.xml deploy -DskipTests=true -B -V
    skip_cleanup: true
    on:
      repo: sbaudoin/sonar-yaml
      branch: master
  # Also deploy tags
  - provider: script
    script: mvn --settings .travis/settings.xml deploy -DskipTests=true -B -V
    skip_cleanup: true
    on:
      repo: sbaudoin/sonar-yaml
      tags: true
  - provider: releases
    api_key:
      secure: "XLPQqb794G1PMULyF0L/2OvZV5S+6UNF/HNxnvS3dBr/uPOZsPnG7Uxg+ywEhWzraPCE3G/IEq8iWvxRl3ktpesGDOgoI4FoIYEu97Qf5xQXtxSPqEzc+4MgBl0iqcUMt7YxG5rQiDmHNFYzQ2ZiFMNHNtv9E5ooerjUpt07PkdpnNECMVpMAal8Qu6YBnyNo5Djxff4PlOBVSpJzNlqzxvrCTI1mX3jlG2qwsS0ajl+LkSuSIPHAwAoiAHmU4Iy861wVL2Yiu6IPYcZKTeWgtJ1p3g2EsP/xYZn/1r9lYnSRl84oPcNRWoDsot67J7HR3p7bBquuOcuqj4ccmSOfI27FGTWzSlPQ5aapuafFfbYFFvpxv25/vJ+H2i4r0+xi4pK1fZaXfIPhq3U1UPVN6PZ27JxsNRTht5lmyJ0S2CLUCKwAWv6ck+GAv4/guxEk+AnePkc0SO8lYAh6Can2B76aFrjPd6K5DpnnbphQBeTk35k3k3lWed4LUjFu4Z2jga+1oreWlGO6aagdEkIL0m0khL5NqO2ijHwPzJIQnuJ2qP59XRAyEhAEKD5gURKT61jcrZ3vYbCLhIb2z/bc9CfjuGMVKx1Xm2VSXswCRC0mOvceLcbxOxo6NnU55e4Obvw5j2UIqFSc7Om2iN44g8Wof6MDJysT0LH7ziDoks="
    file_glob: true
    file:
      - target/sonar-yaml-plugin-*.jar
    skip_cleanup: true
    on:
      repo: sbaudoin/sonar-yaml
      tags: true
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'